apiVersion: v1
kind: Service
metadata:
  name: aquabrainapi
  namespace: aquabrain-api
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: aquabrainapi
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api.jdemmers.dev
  namespace: aquabrain-api
spec:
  secretName: api.jdemmers.dev
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
  - api.jdemmers.dev
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: aquabrainapi-http
  namespace: aquabrain-api
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/`)
    kind: Rule
    services:
    - name: aquabrainapi
      port: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: aquabrainapi
  namespace: aquabrain-api
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`api.jdemmers.dev`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: aquabrainapi
      port: 8080
  tls:
    secretName: api.jdemmers.dev
#---
#apiVersion: autoscaling/v2
#kind: HorizontalPodAutoscaler
#metadata:
  #name: aquabrainapi
  #namespace: aquabrain-api
#spec:
  #scaleTargetRef:
    #apiVersion: apps/v1
    #kind: Deployment
    #name: aquabrainapi
  #minReplicas: 2
  #maxReplicas: 10
  #metrics:
  #- type: Resource
    #resource:
      #name: cpu
      #target:
        #type: Utilization
        #averageUtilization: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aquabrainapi
  namespace: aquabrain-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: aquabrainapi
  template:
    metadata:
      labels:
        app: aquabrainapi
    spec:
      containers:
      - name: aquabrainapi
        image: ghcr.io/jasperdemmers/aquabrainapi:main
        imagePullPolicy: Always
        #resources:
          #requests:
            #cpu: 300m
            #memory: 150Mi
          #limits:
            #cpu: 600m
            #memory: 256Mi
        ports:
        - containerPort: 8080
        env:
        - name: BASIC_AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: basic-auth
              key: USERNAME
        - name: BASIC_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: basic-auth
              key: PASSWORD
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: db-auth
              key: HOST
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-auth
              key: DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-auth
              key: USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-auth
              key: PASSWORD
