logs:
  general:
    level: ERROR

ports:
  web:
    port: 80
    redirectTo:
      port: websecure
  websecure:
    port: 443

ingressRoute:
  dashboard:
    enabled: false

securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0

service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.1.4.200

deployment:
  replicas: 5

ingressClass:
  enabled: true
  isDefaultClass: true