apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-cluster
spec:
  secretName: mysql-secrets
  tlsUseSelfSigned: true
  instances: 5
  router:
    instances: 3
  datadirVolumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "iscsi"
    resources:
      requests:
        storage: 1Gi