- name: Reboot K8s
  hosts:
    - kubecluster
  vars_files:
    - ../secrets.yaml
  vars:
    ansible_become_pass: "{{ vault_become_pass }}"
    ansible_ssh_common_args: '-o UserKnownHostsFile=./known_hosts'
  gather_facts: yes
  connection: ssh
  become: yes
  tasks:   
    - name: Reboot all the kubernetes nodes.
      block:
        - name: Display a message before rebooting
          debug:
            msg: "Rebooting all the kubernetes nodes in 10 seconds."
        - name: Reboot all the kubernetes nodes.
          reboot:
            connect_timeout: 5
            reboot_timeout: 3600
            pre_reboot_delay: 0
            post_reboot_delay: 30
            test_command: whoami