---
- name: Get all folders
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ./vault.yaml
  tasks:
  - name: Get all folders
    vmware.vmware_rest.vcenter_folder_info:
      vcenter_hostname: "{{ vcenter_hostname }}"
      vcenter_username: "{{ vcenter_username }}"
      vcenter_password: "{{ vcenter_password }}"
      vcenter_validate_certs: no
    register: folder_info
  - debug: msg="{{ item.name }}"
    loop: "{{ folder_info.value }}"
    when: folder_info.value is defined