---
- name: Create a VM from a template
  hosts: localhost 
  connection: local
  gather_facts: no
  vars_files:
    - vault.yaml
  vars:
    template_folder: "DMZ/DMZ74222/vlanB"
    template_name: "DMZ74222 - K8s - Template"
    destination_folder: "DMZ/DMZ74222/vlanA"

  tasks:
  - name: Clone the template
    vmware_guest:
      #vCenter specific
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ vcenter_datacenter }}"
      cluster: "{{ vcenter_cluster }}"

      #Template specific
      name: "{{ item.name }}"
      template: "{{ template_name }}"
      folder: "{{ destination_folder }}"
      resource_pool: "{{ vcenter_resource_pool }}"
      datastore: "{{ vcenter_datastore_name }}"

      state: poweredon
      wait_for_ip_address: yes
      #customization:
        #hostname: "{{ item.name }}"
        #dns_servers:
          #- 10.1.0.1
        #dns_suffix:
          #- "aquabrain.lan"
      #networks:
        #- name: "0777_DMZ74222_PVlanB"
          #gateway: "10.1.0.1"
          #ip: "10.1.5.{{ item.ip }}"
          #netmask: "255.255.0.0"  
    loop:
      - { name: "worker02", ip: "1" }
      #- { name: "worker02", ip: "2" }
      #- { name: "worker03", ip: "3" }
    delegate_to: localhost