---
- name: Create a VM from a template
  hosts: localhost 
  connection: local
  gather_facts: no
  vars_files:
    - vault.yaml
  vars:
    vm_folder: "DMZ/DMZ74222/vlanB/Workers"
    vm_name: "DMZ74222 - K8s - Worker05"

  tasks:
  - name: Change hostname of guest machine
    community.vmware.vmware_vm_shell:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vcenter_datacenter }}"
      cluster: "{{ vcenter_cluster }}"
      validate_certs: no

      folder: "{{ vm_folder }}"
      vm_id: "{{ vm_name }}"
      vm_username: admin
      vm_password: AquaBrain#2023!
      vm_shell: "/bin/sh"
      vm_shell_args: "-c 'echo \"something\" > /home/admin/newfile.txt'"
    delegate_to: localhost
    register: shell_command_output
  - name: Show output
    debug:
      msg: "{{ shell_command_output }}"