- hosts: 
    - kubecluster
  vars_files:
    - ../vault.yaml
  vars:
    ansible_become_pass: "{{ vault_become_pass }}"
  gather_facts: yes
  connection: ssh
  
  tasks:
    - name: Hold K8s packages
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - containerd.io
        - kubeadm
        - kubectl
        - kubelet