- hosts: 
    - kubecluster
  vars_files:
    - ../vault.yaml
  vars:
    ansible_become_pass: "{{ vault_become_pass }}"
  gather_facts: yes
  connection: ssh
  
  tasks:
   - name: Remove containerd service
     systemd: 
       name: containerd
       state: stopped
       enabled: no
       daemon-reload: yes

   - name: Unhold containerd
     dpkg_selections:
       name: containerd.io
       selection: install
   
   - name: Uninstall containerd.
     apt:
       pkg: 
         - containerd.io
       state: absent

   - name: Unhold Kubernetes packages
     dpkg_selections:
       name: "{{ item }}"
       selection: install
     loop:
       - kubeadm
       - kubectl
       - kubelet

   - name: Uninstall Kubernetes Cluster Packages.
     apt: 
       name:
         - kubeadm
         - kubectl
         - kubelet
       state: absent

   - name: Remove Docker Repository
     apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
       state: absent
       filename: docker

   - name: Installing prerequisites for Kubernetes
     apt: 
       name:
         - apt-transport-https
         - ca-certificates
         - curl
         - gnupg-agent
         - vim
         - software-properties-common
       state: absent

   - name: Remove Swap entry from /etc/fstab.
     lineinfile:
       dest: /etc/fstab
       regexp: swap
       state: absent

   - name: Make the Swap active
     command: swapon -a

   - name: Disable service kubelet
     service: 
       name: kubelet
       enabled: no
     
# Please exercise caution before initiating a system reboot.
# In a production environment, it could disrupt the system's functionality.
#   - name: Reboot all the kubernetes nodes.
#     reboot:
#       msg: "Reboot initiated by Ansible"
#       connect_timeout: 5
#       reboot_timeout: 3600
#       pre_reboot_delay: 0
#       post_reboot_delay: 30
#       test_command: whoami
